### ISSUE TITLE
`client.group_subscribers(group_id)` returns 100 records if there's more than 100 in the group

### ISSUE THREAD

**Issue by inem** [jpalumickas/mailerlite-ruby#10]
This might be a normal behaviour, but it is not documented.

**Comment by jpalumickas** [comment]
Hey @inem 

This is because Mailerlite using pagination and default limit is 100. You can change this providing `limit` option.

```rb
client.group_subscribers(group_id, limit: 200)
```

Also, Mailerlite accepts `offset` option if you're planning to use your own pagination.

Please let me know if this helped you 😉
