### ISSUE TITLE
Pass limit, offset, or filters?

### ISSUE THREAD

**Issue by zainzafar** [jpalumickas/mailerlite-ruby#14]
`/groups` api endpoint supports passing in limit, offset and filters. One of our users has more than 100 groups and there's no way to currently go through pagination.

**Comment by jpalumickas** [comment]
Hello @zainzafar 

I released a new version **1.8.0** with a fix for this issue. Now you can use filers like this:
```rb
client.groups(limit: 5, offset: 10)
```

Let me know if you will have more issues. 👍
