### ISSUE TITLE
Plan to test and bump faraday gem to '~> 1.0.1'?

### ISSUE THREAD

**Issue by yizeng** [jpalumickas/mailerlite-ruby#17]
Faraday gem has finally released their v1 this year. Any plans to upgrade to it?

**Comment by jpalumickas** [comment]
Hey @yizeng 

I have plan to release with the next version, together with Ruby 2.3 and 2.4 drop. I hope I will do this till the end of next week.

**Comment by yizeng** [comment]
Thanks for the quick reply! Looking forward to it!

**Comment by jpalumickas** [comment]
I will reopen this ticket to keep as a reminder and will close after release 🙂

**Comment by jpalumickas** [comment]
@yizeng released v1.10.0 with Faraday v1
