### ISSUE TITLE
When removing a subscriber from a group, email must be URL encoded

### ISSUE THREAD

**Issue by adonaldson** [jpalumickas/mailerlite-ruby#6]
Hi there,

Firstly, it's been really easy to work with with your gem - good documentation and examples and a clear API. Thanks!

I ran into a problem while removing a subscriber from a group. This endpoint/method:

- http://developers.mailerlite.com/v2/reference#remove-subscriber
- `client.delete_group_subscriber(group_id, email)`

A subscriber with a google `+` style email (e.g. testuser+filter@sendowl.com) can't be removed from a group. My guess is that the `+` gets converted (at their end) into a space.

The solution that worked for me locally was to `CGI::escape` the email before I pass it to `delete_group_subscriber`, however it feels to me like this would be more nicely handled in the gem.

I had a look at the code, and while I'm confident I can make the change, I'm less confident that I'll catch all instances across the codebase where this is a problem and to know how to write a good spec that fits in with the style you already have.

Also, do you want this change in your gem, or would you rather a documentation change that recommends users escape their email before passing it in?

I'm happy to work on this, just would appreciate your thoughts before ploughing on!

**Comment by jpalumickas** [comment]
Hey @adonaldson 

It's good to hear that it's easy to use this gem for you 😉 

Thanks, for information about this email escape problem, I think it would be better to have this fix in the gem, rather than everyone should write this escape.

If you have time, you can open PR for that, or I can do this a bit later for you.

Cheers!

**Comment by adonaldson** [comment]
Can do!
