### ISSUE TITLE
Bad request messages are not being passed through

### ISSUE THREAD

**Issue by adonaldson** [jpalumickas/mailerlite-ruby#9]
Hi there,

I was experiencing some cases where an email address was not added to a list. Checking the logs I saw the error `MailerLite::BadRequest: Missing a required parameter or calling invalid method`

On further digging (and contact with MailerLite) I discovered the cause was that the email I was subscribing had already been added to the (double opt-in) list previously but hadn't yet been confirmed.

You can recreate using the following options in your call to `create_group_subscriber`:

```
{
"email": "your@email.com",
"type": "unconfirmed"
}
```

Then repeating the process with:

```
{
"email": "your@email.com"
}
```

Looking at the code ( https://github.com/jpalumickas/mailerlite-ruby/blob/master/lib/mailerlite/error.rb#L19 ) it seems as though we try to set the message but _something_ happens stopping it, so the user of the library is shown the default message instead.

I'll dig into this a little more when I get some time (unless someone beats me to it), but I just thought I'd share!

Also, I was having difficulty getting raw request/responses out of Faraday (through your gem). Do you have an approach that you use to expose that? It'd make debugging the request/responses in a live application a lot easier!

**Comment by jpalumickas** [comment]
Hey @adonaldson,

With your example I'm getting an error from MailerLite response:
```
MailerLite::BadRequest: Subscriber type is unconfirmed
```

can you confirm that you're using latest gem version?

**Comment by adonaldson** [comment]
You're absolutely right - my mistake. I thought I was up to date but this gem moves fast :)

Thanks!

**Comment by goldenstar999** [comment]
Hi, 
I got error cirecle ci script on git lab
```
$ bundle exec rake db:migrate RAILS_ENV=test
 rake aborted!
 MailerLite::BadRequest: Array[from_name]:
     This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
 /builds/trekview/explorer/.bundle/ruby/2.6.0/gems/mailerlite-1.9.0/lib/mailerlite/middleware/raise_error.rb:13:in `on_complete'
```

How can I solve this issue?
